name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@1.3.1
        with:
          build_configuration: prod
          base_href: /appvision-website/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/appvision-website
