name: Push to Pull Request
on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Angular Application
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Run Build
        run: npm run build -- --configuration=production
